[env:cores3]
build_src_filter = +<main.cpp>
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = m5stack-cores3
framework = arduino
board_build.arduino.memory_type = qio_qspi
monitor_speed = 115200
upload_speed = 921600
lib_ldf_mode = deep+
lib_deps =
    m5stack/M5Unified@0.2.17
    m5stack/M5GFX@0.2.28
    https://github.com/m5stack/M5Faces.git#28188e1820113a2caf1c21b3a948f574f3e535fe
build_flags =
    -I $PROJECT_LIBDEPS_DIR/$PIOENV/M5Unified/src
    -DCORE_DEBUG_LEVEL=1

[env:radio]
extends = env:cores3
extra_scripts = post:tools/patch_audio_stream.py
build_src_filter = +<radio.cpp>
build_flags =
    ${env:cores3.build_flags}
    -I ${platformio.packages_dir}/framework-arduinoespressif32/libraries/Network/src
lib_deps =
    ${env:cores3.lib_deps}
    earlephilhower/ESP8266Audio@2.4.1

[env:controller]
extends = env:cores3
board_build.embed_files =
    assets/home-stage.png
    assets/radio-stage-0.png
    assets/radio-stage-1.png
    assets/radio-stage-2.png
    assets/fonts/faces10.vlw
    assets/fonts/faces12.vlw
    assets/fonts/faces16.vlw
    assets/fonts/faces16regular.vlw
build_src_filter = +<controller.cpp>
build_flags =
    ${env:cores3.build_flags}
    -I ${platformio.packages_dir}/framework-arduinoespressif32/libraries/Network/src

[env:suite]
extends = env:controller
extra_scripts = post:tools/patch_audio_stream.py
board_build.partitions = faces_16MB.csv
build_src_filter = +<launcher.cpp> +<controller.cpp> +<radio.cpp> +<FacesOta.cpp> +<companion.cpp> +<FacesNetwork.cpp> +<FacesConnection.cpp>
build_flags =
    ${env:controller.build_flags}
    -DFACES_SUITE=1
lib_deps =
    ${env:radio.lib_deps}
