"""Keep the approved 320x240 player geometry shared by preview and firmware."""
from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
m=json.loads((root/'ui/music-layout.json').read_text())
lines=['// Generated by tools/build_music_layout.py; edit ui/music-layout.json.','#pragma once','namespace music_layout {']
for key,value in m.items():
 lines.append('constexpr int '+key+('[] = {'+','.join(map(str,value))+'};' if isinstance(value,list) else ' = '+str(value)+';'))
lines.append('}')
(root/'src/MusicLayout.h').write_text('\n'.join(lines)+'\n')
css=f'''/* BEGIN SHARED MUSIC LAYOUT */
.screen[data-app="music"]{{width:{m['width']+20}px;height:{m['height']+20}px}}
.screen[data-app="music"] .content{{position:absolute;left:0;top:28px;width:320px;height:146px;min-height:0}}
.screen[data-app="music"] .meta h2{{line-height:{m['titleLine']}px}}
.screen[data-app="music"] .timeline{{position:absolute;left:{m['timelineX']}px;top:{m['timelineY']}px;width:{m['timelineWidth']}px;height:{m['timelineHeight']}px;margin:0}}
.screen[data-app="music"] .time{{position:absolute;left:0;top:{m['timelineY']+m['timelineHeight']}px;width:320px;height:23px}}
.screen[data-app="music"] .time{{align-items:baseline;line-height:12px}}
.screen[data-app="music"] .controls{{position:absolute;left:{m['buttonX'][0]}px;top:{m['buttonY']}px;width:{m['buttonX'][-1]+m['buttonWidth'][-1]-m['buttonX'][0]}px;height:{m['buttonHeight']}px;padding:0;gap:{m['buttonGap']}px;grid-template-columns:{' '.join(str(w)+'px' for w in m['buttonWidth'])};align-items:stretch;border:0;border-radius:0;background:transparent}}
.screen[data-app="music"] .controls button{{position:relative;display:flex;align-items:center;justify-content:center;min-width:0;width:auto;height:{m['buttonHeight']}px;padding:0;border:1px solid #ffffff38;border-radius:4px;box-shadow:inset 0 1px #ffffff0a;background:#ffffff12;font:12px/16px -apple-system,BlinkMacSystemFont,sans-serif;white-space:nowrap;color:#fff8ed}}
.screen[data-app="music"] .controls button:not(:disabled):hover{{background:#ffffff26;border-color:#ffffff60}}
.screen[data-app="music"] .controls button:not(:disabled):active{{background:#ffffff38;transform:translateY(1px)}}
.screen[data-app="music"] .controls button:focus-visible{{outline:1px solid #f4e8c8;outline-offset:1px}}
.screen[data-app="music"] #homeButton::after{{content:"";position:absolute;left:0;top:0;width:{m['homeTouchWidth']}px;height:{m['homeTouchHeight']}px;z-index:4}}
.screen[data-app="music"] #homeButton:focus-visible::after{{outline:1px solid #f4e8c8;outline-offset:-2px}}
/* END SHARED MUSIC LAYOUT */'''
p=root/'music_bridge/preview.html';s=p.read_text()
if '/* BEGIN SHARED MUSIC LAYOUT */' in s:
 a=s.index('/* BEGIN SHARED MUSIC LAYOUT */');b=s.index('/* END SHARED MUSIC LAYOUT */',a)+len('/* END SHARED MUSIC LAYOUT */');s=s[:a]+css+s[b:]
else:s=s.replace('</style>',css+'\n</style>')
p.write_text(s)
