// Generated by tools/build_paper_home.py from ui/home-layout.json.
#pragma once
#include <cstdint>
namespace home_layout {
struct Card { int x,y,w,h,titleX,titleY,subtitleX,subtitleY,keyX,keyY; const char *title,*subtitle,*key; uint32_t subtitleColor; };
inline constexpr Card cards[] = {
    {8,34,304,92,19,46,19,86,18,99,"MUSIC","MAC REMOTE","M",0x4f4d49},
    {8,132,149,82,17,142,17,175,18,187,"RADIO","INTERNET","R",0x4f4d49},
    {163,132,149,82,172,143,172,175,173,187,"COMPANION","STACKCHAN","A",0x4f4d49},
};
inline constexpr uint32_t paper=0xf4e7d3;
inline constexpr int connectionBottom=34;
inline constexpr int powerRight=312, powerY=11;
inline constexpr const char* hint="IDLE 3 MIN → COMPANION";
}
