// Generated by tools/build_home_art.py from ui/home-layout.json.
#pragma once
#include <cstdint>
namespace home_layout {
struct Card { int x,y,w,h,titleX,titleY,subtitleX,subtitleY,keyX,keyY; const char *title,*subtitle,*key; uint32_t subtitleColor; };
inline constexpr Card cards[] = {
    {14,42,292,78,28,54,28,80,176,54,"音乐遥控器","MAC MUSIC","M",0xbbd4ca},
    {14,128,142,84,26,171,26,195,126,139,"网络收音机","INTERNET RADIO","R",0xc3b394},
    {164,128,142,84,176,171,176,195,276,139,"小伙伴","STACKCHAN","A",0xbdbab8},
};
inline constexpr const char* hint="闲置3分钟，进入小伙伴";
}
