// Generated by tools/build_music_layout.py; edit ui/music-layout.json.
#pragma once
namespace music_layout {
constexpr int width = 320;
constexpr int height = 240;
constexpr int artX = 15;
constexpr int artY = 46;
constexpr int artSize = 112;
constexpr int pausedSize = 96;
constexpr int discSize = 102;
constexpr int discTravel = 24;
constexpr int metaX = 153;
constexpr int metaY = 59;
constexpr int metaWidth = 159;
constexpr int titleLine = 19;
constexpr int artistGap = 3;
constexpr int artistHeight = 14;
constexpr int heartHeight = 20;
constexpr int lyricGap = 5;
constexpr int lyricHeight = 17;
constexpr int timelineX = 10;
constexpr int timelineY = 166;
constexpr int timelineWidth = 300;
constexpr int timelineHeight = 4;
constexpr int timeY = 179;
constexpr int buttonY = 202;
constexpr int buttonHeight = 30;
constexpr int buttonX[] = {7,62,121,176,223,270};
constexpr int buttonWidth[] = {52,56,52,44,44,43};
constexpr int homeTouchWidth = 145;
constexpr int homeTouchHeight = 161;
constexpr int buttonCount = 6;
constexpr int buttonGap = 3;
constexpr int statusLeft = 176;
constexpr int powerRight = 312;
constexpr int powerY = 12;
constexpr int sourceRight = 175;
constexpr int powerGap = 4;
}
