// Generated by tools/build_music_layout.py; edit ui/music-layout.json.
#pragma once
namespace music_layout {
constexpr int width = 320;
constexpr int height = 240;
constexpr int artX = 10;
constexpr int artY = 36;
constexpr int artSize = 128;
constexpr int pausedSize = 110;
constexpr int discSize = 116;
constexpr int discTravel = 27;
constexpr int metaX = 150;
constexpr int metaY = 42;
constexpr int metaWidth = 160;
constexpr int titleLine = 22;
constexpr int artistGap = 3;
constexpr int artistHeight = 18;
constexpr int heartHeight = 30;
constexpr int lyricGap = 5;
constexpr int lyricHeight = 20;
constexpr int timelineX = 10;
constexpr int timelineY = 174;
constexpr int timelineWidth = 300;
constexpr int timelineHeight = 3;
constexpr int timeY = 183;
constexpr int buttonY = 200;
constexpr int buttonHeight = 30;
constexpr int buttonX[] = {7,62,121,176,223,270};
constexpr int buttonWidth[] = {52,56,52,44,44,43};
constexpr int homeTouchWidth = 144;
constexpr int homeTouchHeight = 168;
constexpr int buttonCount = 6;
constexpr int buttonGap = 3;
}
