// Generated by tools/build_paper_radio.py from ui/radio-layout.json.
#pragma once
namespace radio_layout {
struct Rect { int x,y,w,h; constexpr bool contains(int px,int py) const {return px>=x&&px<x+w&&py>=y&&py<y+h;} };
inline constexpr Rect home={0,0,144,39};
inline constexpr Rect play={8,113,144,33};
inline constexpr Rect connection={0,217,96,23};
inline constexpr Rect volumeDown={164,217,34,23};
inline constexpr Rect volumeUp={282,217,38,23};
inline constexpr Rect stations[]={{8,173,98,42},{111,173,98,42},{214,173,98,42}};
inline constexpr int needleX[]={255,275,295};
inline constexpr int needleY=109;
inline constexpr int needleHeight=25;
inline constexpr int powerRight=312;
inline constexpr int powerY=12;
inline constexpr int stationAt(int x,int y){for(int i=0;i<3;++i)if(stations[i].contains(x,y))return i;return -1;}
}
